server:
    port: 8090

spring:
    application:
        name: ms-mascotas
    datasource:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://veterinaria-inteligente-server.database.windows.net:1433;databaseName=veterinaria-bd;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30
        username: veterinaria-admin
        password: {your_password_here}
    jpa:
        hibernate:
            ddl-auto: create
        database: default
        database-platform: org.hibernate.dialect.SQLServerDialect
    config:
        import: optional:configserver:http://localhost:8888

eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/